### PR TITLE
Added new maps and a sample html file

### PR DESCRIPTION
**Pull request by adeelnawaz**
I have added maps for six continents (extracted from jqv world map) in /maps/continents directory, and added a sample continents.html file in /samples directory

### CODE REVIEW

**Comment by loren138** [comment]
@adeelnawaz I realize you made this all a while ago, but I was wondering if you had a program to exclude/scale things.  I want to make a map from the world map of a select few countries (middle east, North Africa, and Turkey).

**Comment by adeelnawaz** [comment]
@loren138 sure!
If you take a look at jqvmap/maps/ directory, you'll find js files for all maps.
https://raw.githubusercontent.com/manifestinteractive/jqvmap/stable/jqvmap/maps/jquery.vmap.world.js

This file contains a JSON for the whole world, with JSONs of each country included in it. You can just remove the ones you don't want and it will work. To scale / edit the map, you'll need to do the following:

# Save the output of jqvmap (HTML svg tag) in a .svg file
# Use an SVG editor to edit that file. It will give you drawing interface to edit the map
# Save the changes, then open the .svg file in a text editor
# Copy and replace the svg strings in js file from .svg file

**Comment by manifestinteractive** [comment]
@adeelnawaz Thanks for the tip.  BTW, would you be interested in being a collaborator on this project?  I have not used it in over a year but need some developers to help maintain pull requests.  Lot's of good stuff being committed ( thanks, BTW ) but I seldom have time to check each PR.

**Comment by adeelnawaz** [comment]
Sure, but I too have very little time to spare. Still I'll do what I can to help this project.

**Pull request merged**
