### PR TITLE
new brazilian file

### PR DESCRIPTION
**Pull request by elmeerr**
New file for brazilian map, to add better stroke/outline in states borders. Related to issue #228
Also, the file was improved, reduced from +2mb to 145kb.

### CODE REVIEW

**Comment by manifestinteractive** [comment]
Looks like this fails some unit tests.  I will take a look at this file to see why it is not passing the tests.

**Comment by elmeerr** [comment]
I think its because I didn't add test command...this "ci/circleci" it's completely new to me....I don't know it works. Let me know if something beyond that is wrong. (I'm not used doing this procedure)

**Comment by manifestinteractive** [comment]
Circle CI would only fail if the unit tests failed.  So there is likely a basic JS issue we can look at.

**Comment by elmeerr** [comment]
is there a way to check Circle CI before of a commit?

**Comment by manifestinteractive** [comment]
Yam just run `npm test` in the project directory in your terminal.  If it fails, it will tell you why.  That is what Circle CI is doing, running that test.  If the test fails, the check fails :(

**Comment by elmeerr** [comment]
I'm getting this erro when I try to run `npm test`
erro_npm


Do you know what could it be?

**Comment by manifestinteractive** [comment]
Looks like you did not run `npm install` first

More than likely the file has some linting issue, which `npm test` will pinpoint.  But that test wont run unless the node packages are installed first.

**Comment by elmeerr** [comment]
I ran npm install, delete node_modules, run npm install again, even so, I got the same message in the print that I've posted. I have windows 10 running in my notebook...I tried to search on google but I found nothing relative to this error. =(

**Comment by manifestinteractive** [comment]
I just manually pulled this in, since for some reason there was an issue with branches.  It is now in our `master` branch.

**Comment by elmeerr** [comment]
Ok! thanks, @manifestinteractive. 

Kind regards,

**Pull request closed without merging**
