### PR TITLE
feat(app): add bower.json with jquery dependencies

### LINKED ISSUE #105: [enhancement] Add missing bower.json.
#### Hey, maintainer(s) of manifestinteractive/jqvmap!

We at [VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) are working hard to keep up the quality of the bower's registry.

We just finished our initial analysis of the quality of the Bower.io registry:

**7530** - registered packages, *224* of them doesnt exists anymore;

We analysed **7306**  existing packages and  **1070** of them don't have bower.json on the master branch ( _that's where a Bower client pulls a data_ ).

Sadly, your library `manifestinteractive/jqvmap` is one of them.

Can you spare **15** minutes to help us to make Bower better?

Just add a new file `bower.json` and  change attributes.

```
{
  "name": "manifestinteractive/jqvmap",
  "version": "1.0.0",
  "main": "path/to/main.css",
  "description": "please add it",
  "license": "Eclipse",
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
    "<dependency_name>": "<semantic_version>",
    "<dependency_name>": "<Local_folder>",
    "<dependency_name>": "<package>"
  },
  "devDependencies": {
    "<test-framework-name>": "<version>"
  }
}

```

Read more about bower.json [on the official spefication](http://bower.io/#defining-a-package) and nodejs [semver](https://github.com/isaacs/node-semver#ranges) library has great examples of proper versioning.

**NB!** Please _validate_ your bower.json with _jsonlint_ before commiting your updates.

Thank you!

Timo,
twitter: @versioneye
email: timo@versioneye.com
[VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) - no more legacy software!

### PR DESCRIPTION
**Pull request by zhuangya**
fix #105

### CODE REVIEW

**Comment by manifestinteractive** [comment]
This ticket was automatically closed because it was tied to a branch that no longer exists ( unknown result of deleting a branch with issues tied to it ).

If someone wants to create a new PR on the master branch with the new file, I will be happy to review it.

**Comment by zhuangya** [comment]
i'm working on it(again) right now :)

**Comment by manifestinteractive** [comment]
Sorry for the delay on it, I had to move cross country for a job, and once I moved the company closed up shop ... so there was a bit of a struggle on my end for a bit to get things sorted.  I tried contacting a few people who contributed to this project to see if they would not mind taking on some responsibilities to maintain it, but I have yet to find another person to volunteer.

Life Happens :) Having a few other people to help sort out these issues would make everything run a little smoother.  Let me know if anyone reading this would like to be added to the contributor list.

**Comment by zhuangya** [comment]
> Sorry for the delay on it, I had to move cross country for a job, and once I moved the company closed up shop ... so there was a bit of a struggle on my end for a bit to get things sorted. I tried contacting a few people who contributed to this project to see if they would not mind taking on some responsibilities to maintain it, but I have yet to find another person to volunteer.
> 
> Life Happens :) Having a few other people to help sort out these issues would make everything run a little smoother. Let me know if anyone reading this would like to be added to the contributor list.

that's alright 

sorry for my bad aptitude earlier :-1: for me.

and i think i can try to be a volunteer for this project

**Comment by manifestinteractive** [comment]
@zhuangya it's all good.  I know how frustrating it is to contribute to projects that just kind of "go away".  Mine was certainly not by choice, I just kind of got stuck in a weird place there for a bit and had to get my stuff sorted.  No hard feelings.  I've heard way worse from others, trust me ;)

I'll add you to the contributors list, which will allow you to manage the project just as I am.  If you need help, just hit me up with an @ mention and I will chime in.  I tried to make the project a little easier to maintain by adding ESLinting rules and CircleCI checks on code quality.  Bottom line, a Merge Request will fail if it does not pass coding standard covered in the CONTRIBUTING.md file

**Comment by zhuangya** [comment]
@manifestinteractive roger that!

**Comment by zhuangya** [comment]
@manifestinteractive and, btw, `jqvmap` should publish to bower, would you please do that?

**Comment by manifestinteractive** [comment]
Done.

```bash
bower info jqvmap
```

**Comment by manifestinteractive** [comment]
Had to update the bower.json file to be correct, and rename the git tag to their standards... but you should be good to go.

**Comment by zhuangya** [comment]
works for me :+1:

**Pull request closed without merging**
